#!/usr/bin/env bash
# Script to install and configure Nginx to serve "Hello World!

# Update and install nginx
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'nginx HTTP'

# Create the html page
sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Redirecting
NGINX_CONFIG="/etc/nginx/sites-available/default"
sudo sed -i '/server {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=EDAjqGcayKs;\n\t}' "$NGINX_CONFIG"

# Restart nginx
service nginx restart
