#!/usr/bin/env bash
# A Bash script that installs nginx, configure /redirect_me
# as a 301 moved permanently and include a 404 page.


"""
Install nginx
Configure /redirect_me as a 301 moved permanently
Include a 404 page 
"""

apt-get update
apt-get install nginx
mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;

    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://www.youtube.com/;
    }

    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
