#!/usr/bin/env bash
# This bash script pings an IP address passed as an argument.


# Check if an argument was passed to the script
if [ -z "$1" ]; then
  # Display usage if no argument is given then exit
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"
