#!/usr/bin/env bash
# configure nginx to listen on port 80

# remove the old default nginx
rm /etc/nginx/sites-enabled/default
# configure nginx
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
