#!/usr/bin/env bash
# This is a script that is used to kill a running pid

# Get the PID of the process named 4-to_infinity_and_beyond
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process was found
if [ -n "$pid" ]; then
    # Kill the process
    kill "$pid"
else
    echo "4-to_infinity_and_beyond process not found."
fi
