#!/usr/bin/env bash
# This script displays the content of the current directory
# In a list format, showing only the part of each name after the first dash.

for file in *; do
    if [[ -f $file && $file != .* ]]; then
        # Extract part of the filename after the first dash.
        name="${file#*-}"
        echo "$name"
    fi
done

