#!/usr/bin/env bash
# The script changes the IP address of localhost and facebook.com


if [ "$EUID" -ne 0 ]; then
	echo "please run as root"
	exit 1

fi

# Back up the current etc/hosts file
cp /etc/hosts /etc/hosts.old

# Update /etc/host with the new entries
{
	echo "127.0.0.2 localhost"
	echo "8.8.8.8 facebook.com"
} >> /etc/hosts
