#!/usr/bin/env bash
# This bash script displays all active IPv4 IP on the machine it's executed on


# Display all active IPv4 IP address
ip -4 addr show | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $2}'
