#!/usr/bin/env bash
# Update package list
sudo apt-get update

#Install apache
sudo apt-get install -y apache2

# Start apache
service apache2 start

#Create a page
echo "Hello ALX" > /var/www/html/index.html

