#!/usr/bin/env bash
#  Run Nginx as Nginx

# Make nginx run like nginx
sudo sed -i 's/user www-data/user nginx;/' /etc/nginx/nginx.conf

# Make nginx listen to port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart nginx
sudo -u nginx service nginx restart
