#!/usr/bin/env bash
#  Run Nginx as Nginx

# Make nginx run like nginx
sudo sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Make nginx listen to port 8080
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
